[2022-10-05 18:25:04,543] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_rappers_dag.load_rappers manual__2022-10-05T18:25:02.565825+00:00 [queued]>
[2022-10-05 18:25:04,551] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_rappers_dag.load_rappers manual__2022-10-05T18:25:02.565825+00:00 [queued]>
[2022-10-05 18:25:04,551] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-05 18:25:04,551] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-05 18:25:04,551] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-05 18:25:04,564] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): load_rappers> on 2022-10-05 18:25:02.565825+00:00
[2022-10-05 18:25:04,567] {standard_task_runner.py:52} INFO - Started process 292 to run task
[2022-10-05 18:25:04,571] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_rappers_dag', 'load_rappers', 'manual__2022-10-05T18:25:02.565825+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/load_rappers_dag.py', '--cfg-path', '/tmp/tmpp9n1ey_b', '--error-file', '/tmp/tmphg1_45wy']
[2022-10-05 18:25:04,572] {standard_task_runner.py:80} INFO - Job 27: Subtask load_rappers
[2022-10-05 18:25:04,630] {task_command.py:369} INFO - Running <TaskInstance: load_rappers_dag.load_rappers manual__2022-10-05T18:25:02.565825+00:00 [running]> on host 39b88b75de04
[2022-10-05 18:25:04,707] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_rappers_dag
AIRFLOW_CTX_TASK_ID=load_rappers
AIRFLOW_CTX_EXECUTION_DATE=2022-10-05T18:25:02.565825+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-05T18:25:02.565825+00:00
[2022-10-05 18:25:04,708] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-05 18:25:04,709] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 home/fuwilliam/***/scripts/test.py']
[2022-10-05 18:25:04,717] {subprocess.py:85} INFO - Output:
[2022-10-05 18:25:04,784] {subprocess.py:92} INFO - python3: can't open file 'home/fuwilliam/***/scripts/test.py': [Errno 2] No such file or directory
[2022-10-05 18:25:04,786] {subprocess.py:96} INFO - Command exited with return code 2
[2022-10-05 18:25:04,799] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-10-05 18:25:04,802] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=load_rappers_dag, task_id=load_rappers, execution_date=20221005T182502, start_date=20221005T182504, end_date=20221005T182504
[2022-10-05 18:25:04,814] {standard_task_runner.py:97} ERROR - Failed to execute job 27 for task load_rappers (Bash command failed. The command returned a non-zero exit code 2.; 292)
[2022-10-05 18:25:04,824] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-05 18:25:04,860] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
