[2022-10-15 21:10:41,017] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_rappers_dag_pyop.load_tracks_to_gcs manual__2022-10-15T21:10:22.735882+00:00 [queued]>
[2022-10-15 21:10:41,028] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_rappers_dag_pyop.load_tracks_to_gcs manual__2022-10-15T21:10:22.735882+00:00 [queued]>
[2022-10-15 21:10:41,028] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-15 21:10:41,028] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-15 21:10:41,028] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-15 21:10:41,048] {taskinstance.py:1377} INFO - Executing <Task(PostgresToGCSOperator): load_tracks_to_gcs> on 2022-10-15 21:10:22.735882+00:00
[2022-10-15 21:10:41,055] {standard_task_runner.py:52} INFO - Started process 5705 to run task
[2022-10-15 21:10:41,066] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_rappers_dag_pyop', 'load_tracks_to_gcs', 'manual__2022-10-15T21:10:22.735882+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/load_rappers_dag_pyop.py', '--cfg-path', '/tmp/tmpeo9w_ikw', '--error-file', '/tmp/tmp89nw0ibw']
[2022-10-15 21:10:41,067] {standard_task_runner.py:80} INFO - Job 14: Subtask load_tracks_to_gcs
[2022-10-15 21:10:41,177] {task_command.py:369} INFO - Running <TaskInstance: load_rappers_dag_pyop.load_tracks_to_gcs manual__2022-10-15T21:10:22.735882+00:00 [running]> on host 6300e87c6973
[2022-10-15 21:10:41,807] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_rappers_dag_pyop
AIRFLOW_CTX_TASK_ID=load_tracks_to_gcs
AIRFLOW_CTX_EXECUTION_DATE=2022-10-15T21:10:22.735882+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-15T21:10:22.735882+00:00
[2022-10-15 21:10:41,810] {sql_to_gcs.py:139} INFO - Executing query
[2022-10-15 21:10:41,841] {base.py:68} INFO - Using connection ID 'postgres-dc' for task execution.
[2022-10-15 21:10:41,887] {sql_to_gcs.py:155} INFO - Writing local data files
[2022-10-15 21:10:41,893] {sql_to_gcs.py:160} INFO - Uploading chunk file #0 to GCS.
[2022-10-15 21:10:41,945] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/sql_to_gcs.py", line 161, in execute
    self._upload_to_gcs(file_to_upload)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/sql_to_gcs.py", line 351, in _upload_to_gcs
    impersonation_chain=self.impersonation_chain,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 152, in __init__
    impersonation_chain=impersonation_chain,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 219, in __init__
    self.extras = self.get_connection(self.gcp_conn_id).extra_dejson  # type: Dict
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `google_cloud_default` isn't defined
[2022-10-15 21:10:41,949] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=load_rappers_dag_pyop, task_id=load_tracks_to_gcs, execution_date=20221015T211022, start_date=20221015T211041, end_date=20221015T211041
[2022-10-15 21:10:41,967] {standard_task_runner.py:97} ERROR - Failed to execute job 14 for task load_tracks_to_gcs (The conn_id `google_cloud_default` isn't defined; 5705)
[2022-10-15 21:10:42,003] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-15 21:10:42,038] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
