[2022-10-15 15:05:05,945] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_rappers_dag_pyop.load_rappers_to_gcs manual__2022-10-15T15:04:49.494165+00:00 [queued]>
[2022-10-15 15:05:05,955] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_rappers_dag_pyop.load_rappers_to_gcs manual__2022-10-15T15:04:49.494165+00:00 [queued]>
[2022-10-15 15:05:05,955] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-15 15:05:05,955] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-15 15:05:05,955] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-15 15:05:05,970] {taskinstance.py:1377} INFO - Executing <Task(PostgresToGCSOperator): load_rappers_to_gcs> on 2022-10-15 15:04:49.494165+00:00
[2022-10-15 15:05:05,978] {standard_task_runner.py:52} INFO - Started process 775 to run task
[2022-10-15 15:05:05,984] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_rappers_dag_pyop', 'load_rappers_to_gcs', 'manual__2022-10-15T15:04:49.494165+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/load_rappers_dag_pyop.py', '--cfg-path', '/tmp/tmplynl9_sl', '--error-file', '/tmp/tmp0t5ouoie']
[2022-10-15 15:05:05,985] {standard_task_runner.py:80} INFO - Job 8: Subtask load_rappers_to_gcs
[2022-10-15 15:05:06,077] {task_command.py:369} INFO - Running <TaskInstance: load_rappers_dag_pyop.load_rappers_to_gcs manual__2022-10-15T15:04:49.494165+00:00 [running]> on host 6300e87c6973
[2022-10-15 15:05:06,165] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_rappers_dag_pyop
AIRFLOW_CTX_TASK_ID=load_rappers_to_gcs
AIRFLOW_CTX_EXECUTION_DATE=2022-10-15T15:04:49.494165+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-15T15:04:49.494165+00:00
[2022-10-15 15:05:06,166] {sql_to_gcs.py:139} INFO - Executing query
[2022-10-15 15:05:06,200] {base.py:68} INFO - Using connection ID 'postgres-dc' for task execution.
[2022-10-15 15:05:06,201] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/sql_to_gcs.py", line 140, in execute
    cursor = self.query()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/postgres_to_gcs.py", line 116, in query
    conn = hook.get_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 113, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "127.0.0.1", port 5555 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2022-10-15 15:05:06,214] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=load_rappers_dag_pyop, task_id=load_rappers_to_gcs, execution_date=20221015T150449, start_date=20221015T150505, end_date=20221015T150506
[2022-10-15 15:05:06,228] {standard_task_runner.py:97} ERROR - Failed to execute job 8 for task load_rappers_to_gcs (connection to server at "127.0.0.1", port 5555 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 775)
[2022-10-15 15:05:06,278] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-15 15:05:06,344] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
