[2022-10-05 18:22:24,093] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_rappers_dag.load_rappers manual__2022-10-05T18:22:22.876675+00:00 [queued]>
[2022-10-05 18:22:24,108] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_rappers_dag.load_rappers manual__2022-10-05T18:22:22.876675+00:00 [queued]>
[2022-10-05 18:22:24,108] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-05 18:22:24,108] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-05 18:22:24,108] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-05 18:22:24,128] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): load_rappers> on 2022-10-05 18:22:22.876675+00:00
[2022-10-05 18:22:24,133] {standard_task_runner.py:52} INFO - Started process 223 to run task
[2022-10-05 18:22:24,138] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_rappers_dag', 'load_rappers', 'manual__2022-10-05T18:22:22.876675+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/load_rappers_dag.py', '--cfg-path', '/tmp/tmpoofb3o65', '--error-file', '/tmp/tmpdm0u0syx']
[2022-10-05 18:22:24,139] {standard_task_runner.py:80} INFO - Job 24: Subtask load_rappers
[2022-10-05 18:22:24,523] {task_command.py:369} INFO - Running <TaskInstance: load_rappers_dag.load_rappers manual__2022-10-05T18:22:22.876675+00:00 [running]> on host 39b88b75de04
[2022-10-05 18:22:24,816] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_rappers_dag
AIRFLOW_CTX_TASK_ID=load_rappers
AIRFLOW_CTX_EXECUTION_DATE=2022-10-05T18:22:22.876675+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-05T18:22:22.876675+00:00
[2022-10-05 18:22:24,818] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-10-05 18:22:24,819] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 home/fuwilliam/***/scripts/load_rappers.py']
[2022-10-05 18:22:24,841] {subprocess.py:85} INFO - Output:
[2022-10-05 18:22:25,053] {subprocess.py:92} INFO - python3: can't open file 'home/fuwilliam/***/scripts/load_rappers.py': [Errno 2] No such file or directory
[2022-10-05 18:22:25,056] {subprocess.py:96} INFO - Command exited with return code 2
[2022-10-05 18:22:25,071] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-10-05 18:22:25,077] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=load_rappers_dag, task_id=load_rappers, execution_date=20221005T182222, start_date=20221005T182224, end_date=20221005T182225
[2022-10-05 18:22:25,094] {standard_task_runner.py:97} ERROR - Failed to execute job 24 for task load_rappers (Bash command failed. The command returned a non-zero exit code 2.; 223)
[2022-10-05 18:22:25,113] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-05 18:22:25,161] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
